Repository RecoveryLoid/carpitec43, pull requests merged in 2022-10, with the labels that each got.

#12 [Css,Html]Refactorizar footer, agregar nueva estructura
  css/styles.css
  img/disco.svg
  index.html
  views/conocenos.html
  views/contactanos.html
  views/politica_de_privacidad.html
  views/terminos_de_uso.html
  views/terminos_y_condiciones.html
Labels: Approved

#29 [HTML,CSS] se modifico el texto, se modifico el tamaño del titulo, se…
  css/styles.css
  index.html
Labels: En Progreso

#28 [css] Titulo arreglado #issue-13
  css/styles.css
  index.html
Labels: To test
